services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - 6379:6379
  app:
    build: .
    ports:
      - "127.0.0.1:9927:9927"
    depends_on:
      - rabbitmq
      - redis
    command: tail -f /unfazed_taskiq/README.md
    volumes:
      - .:/unfazed_taskiq
